version: '3.8'

networks:
  frontend:
    driver: bridge
  admin_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  internal_network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.169.100.0/24


services:
  # Public-facing vulnerable web application
  vulnerable-app:
    build: 
      context: ./vulnerable-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - frontend
      - admin_network
    depends_on:
      - nginx-proxy
    environment:
      - INTERNAL_SERVICE_URL=http://nginx-proxy:80
  nginx-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - admin_network
    depends_on:
      - admin-service

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    networks:
      admin_network:
        ipv4_address: 192.168.100.10
      internal_network:
        ipv4_address: 192.169.100.10
  internal-service:
    build:
      context: ./internal-service
      dockerfile: Dockerfile
    networks:
      internal_network:
        ipv4_address: 192.169.100.11
